<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  ' View Details' => '',
  'Active Theme Settings' => '',
  'Add a link to a youtube, vimeo, or vine video' => '',
  'Add new Card' => '',
  'Allow Comments' => '',
  'Analytics' => '',
  'Appearance' => '',
  'Categories' => '',
  'Change Information for User' => '',
  'Change the User\'s Email Address' => '',
  'Change the User\'s Password' => '',
  'Change the User\'s Personal Details' => '',
  'CiiMS Dashboard | {{pagetitle}}' => '',
  'Create New Category' => '',
  'Create New User' => '',
  'Create a New Content Category' => '',
  'Create a New User' => '',
  'Delete Category' => '',
  'Disable Comments' => '',
  'Do you want to permanently delete "{{entry}}"?' => '',
  'Draft' => '',
  'Email Settings' => '',
  'Entry Options' => '',
  'Find a category...' => '',
  'Find a user...' => '',
  'General Settings' => '',
  'Hi' => '',
  'In Review' => '',
  'Invite a Friend to Collaborate on this Blog' => '',
  'Modify Category' => '',
  'Modify a Category' => '',
  'No I don\'t. Leave it be.' => '',
  'Plugins' => '',
  'Publish' => '',
  'Published' => '',
  'Reschedule' => '',
  'Revision' => '',
  'Revision: {id}' => '',
  'Rolling back to revision {id} will erase any autosave drafts. Are you sure you want to rollback to this revision?' => '',
  'Schedule' => '',
  'Scheduled' => '',
  'Scheduled For {{date}}' => '',
  'Search for an Entry' => '',
  'Select a Category' => '',
  'Send Invitation' => '',
  'Social Settings' => '',
  'Status' => '',
  'Tags' => '',
  'Title' => '',
  'Update User' => '',
  'Upload Video' => '',
  'Upload a Cover Image' => '',
  'Upload a Cover Video' => '',
  'Users' => '',
  'Words' => '',
  'Yes I do. Make it go away.' => '',
  '{{greeting}}, {{user}}' => '',
);
